In [11]:
# menghapus mising values (drop NaN) 
# import modules

import pandas as pd
import numpy as np

# contoh kode yang tertulis salah sehingga diganti 

# Code :
# import pandas as pd
# print(pd.__version__)

In [8]:
# persiapan data frame

## DEPRICATED ##
# df = pd.util.testing.makeMissingDataframe().reset_index() 
# df.head()

n_rows = 30
n_cols = 4
cols = ['A', 'B', 'C', 'D']

df = pd.DataFrame(np.random.randn(n_rows, n_cols), columns=cols)

nan_mask = np.random.rand(n_rows, n_cols) < 0.2
df[nan_mask] = np.nan

df = df.reset_index()
df.head()

   index         A         B         C         D
0      0 -0.021268  0.593634 -0.460893  0.054558
1      1  0.962758  1.321022       NaN  1.247824
2      2       NaN       NaN  0.083802  1.348722
3      3 -0.915673 -0.224371  0.502846 -0.738695
4      4 -0.794899       NaN  0.121785 -0.624193

In [9]:
df = df.rename(columns={'index':'Z'})
df.head()

   Z         A         B         C         D
0  0 -0.021268  0.593634 -0.460893  0.054558
1  1  0.962758  1.321022       NaN  1.247824
2  2       NaN       NaN  0.083802  1.348722
3  3 -0.915673 -0.224371  0.502846 -0.738695
4  4 -0.794899       NaN  0.121785 -0.624193

In [10]:
df_backup = df.copy(deep=True)