In [1]:
# periksa keamanan antara 2 buah kolom (series) pada data frame
# import modules
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
# persiapan data frame
data = {'A':[15, 15, 18, np.nan, 12], 
        'B':[15, 15, 18, np.nan, 12]}

df = pd.DataFrame(data)
df

      A     B
0  15.0  15.0
1  15.0  15.0
2  18.0  18.0
3   NaN   NaN
4  12.0  12.0

In [3]:
# pandas series
df['A']

0    15.0
1    15.0
2    18.0
3     NaN
4    12.0
Name: A, dtype: float64

In [4]:
df['A']

0    15.0
1    15.0
2    18.0
3     NaN
4    12.0
Name: A, dtype: float64

In [5]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# periksa kesamaan operator ==
df['A'] == df['B']

In [ ]:
# periksa kesamaan dengan method equals ()
df['A'].equals(df['B'])

In [6]:
# periksa kesamaan antar 2 data frame
df1 = df.copy(deep=True)

df.equals(df1)

True

In [7]:
df == df1

       A      B
0   True   True
1   True   True
2   True   True
3  False  False
4   True   True