In [7]:
# membagi data frame menjadi 2 (acak)
# import modules

import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [8]:
# persiapan data frame
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   5  11   8  19  11
1  11  16   1   3   4
2  13   7  19   5  14
3  12  14   7  14  10
4  10  14  17  17   5
5  16  18   6  19  17
6   5  14   3   7  13
7   7  11  19   2   6
8  12  13  10  10  18
9  12  14   6   8   9

In [9]:
# membagi data frame menjadi 2 secara acak berdasarkan proporsi tertentu
df.shape

(10, 5)

In [10]:
proporsi = 0.7
df_1 = df.sample(frac=proporsi)
df_2 = df.drop(df_1.index)

print(f'df_1 shape: {df_1.shape}')
print(f'df_2 shape: {df_2.shape}')

df_1 shape: (7, 5)
df_2 shape: (3, 5)

In [11]:
df_1

    A   B   C   D   E
1  11  16   1   3   4
5  16  18   6  19  17
4  10  14  17  17   5
9  12  14   6   8   9
2  13   7  19   5  14
6   5  14   3   7  13
3  12  14   7  14  10

In [12]:
df_2

    A   B   C   D   E
0   5  11   8  19  11
7   7  11  19   2   6
8  12  13  10  10  18