In [16]:
# seleksi kolom dan baris pada data frame menggunakan loc
# import modules
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [17]:
# persiapan data frame
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0  19  14  19   1  17
1   8  15  19   4  10
2  18  14  15  11  16
3  10   6   4  13   9
4  19  11   1   1   5
5  14  14   7   4  11
6   3  15  18  12  12
7  18  10   5  14  18
8  12  18  12  16  15
9   3  13   6  10   4

In [18]:
# seleksi kolom dan baris dengan loc
df.loc[[0,3,4], ['B','E']]

    B   E
0  14  17
3   6   9
4  11   5

In [19]:
# seleksi baris dengan kondisi 
df.loc[df['B']>10, ['B','D','E']]

    B   D   E
0  14   1  17
1  15   4  10
2  14  11  16
4  11   1   5
5  14   4  11
6  15  12  12
8  18  16  15
9  13  10   4

In [20]:
# slicing data frame dengan loc 
df.loc[0:4, 'B':'D']

    B   C   D
0  14  19   1
1  15  19   4
2  14  15  11
3   6   4  13
4  11   1   1