In [1]:
# konversi nilai numerik kedalam kategori 
# import modules

import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
# persiapan data frame
n_rows = 10
n_cols = 1
cols = ('usia',)

df = pd.DataFrame(np.random.randint(1, 99, size=(n_rows, n_cols)), 
                  columns=cols)
df

   usia
0    97
1    94
2    39
3    22
4    78
5    25
6    29
7    26
8    19
9    66

In [3]:
# pengelompokkan nilai numerik ke dalam beberapa kategori menggunakan cut ()
df['kelompok_usia'] = pd.cut(df['usia'], 
                             bins=[0, 18, 65, 99], 
                             labels=['anak', 'dewasa', 'manula'])
df

   usia kelompok_usia
0    97        manula
1    94        manula
2    39        dewasa
3    22        dewasa
4    78        manula
5    25        dewasa
6    29        dewasa
7    26        dewasa
8    19        dewasa
9    66        manula