In [1]:
# merge 2 data frame
# import modules

import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
# persiapan data frame
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   4  14   7   3  16
1  17  16   6  16  14
2   8  10  18  14  17
3  12   6   6   5   2
4   9  18   4   6  17

In [3]:
df1 = df.copy(deep=True)
df1 = df1.drop([1, 4])
df1

    A   B   C   D   E
0   4  14   7   3  16
2   8  10  18  14  17
3  12   6   6   5   2

In [4]:
df2 = df.copy(deep=True)
df2 = df2.drop([0, 3])
df2

    A   B   C   D   E
1  17  16   6  16  14
2   8  10  18  14  17
4   9  18   4   6  17

In [5]:
# gabung 2 data frame

df_inner = pd.merge(df1, df2, how='inner')
df_inner

   A   B   C   D   E
0  8  10  18  14  17

In [6]:
df_outer = pd.merge(df1, df2, how='outer')
df_outer

    A   B   C   D   E
0   4  14   7   3  16
1   8  10  18  14  17
2   9  18   4   6  17
3  12   6   6   5   2
4  17  16   6  16  14