In [1]:
# weekdays dan weekends (time series)
# import modules
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
# persiapan data frame

## DEPRECATED ##
# n_rows = 365
# n_cols = 2
# cols = ['col1', 'col2']

# df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
#                   columns=cols)

# df.index = pd.util.testing.makeDateIndex(n_rows, freq='D')
# df

n_rows = 365
n_cols = 2
cols = ['col1', 'col2']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')

print(df)

            col1  col2
2024-01-01     4    17
2024-01-02    18    19
2024-01-03     2     4
2024-01-04    10    19
2024-01-05    19    17
...          ...   ...
2024-12-26     9     1
2024-12-27    18    14
2024-12-28    15     5
2024-12-29    18     7
2024-12-30     7    15

[365 rows x 2 columns]

In [3]:
# weekdays dan weekends (time series)
weekdays_df = df[df.index.dayofweek.isin([0, 1, 2, 3, 4])]
weekdays_df.head(7)

            col1  col2
2024-01-01     4    17
2024-01-02    18    19
2024-01-03     2     4
2024-01-04    10    19
2024-01-05    19    17
2024-01-08    15    13
2024-01-09    19     7

In [4]:
weekends_df = df[df.index.dayofweek.isin([5, 6])]
weekends_df.head(7)

            col1  col2
2024-01-06    13     2
2024-01-07     7     2
2024-01-13     3     4
2024-01-14     1    10
2024-01-20     4     4
2024-01-21    15    15
2024-01-27     3     9